namespace AsteriskAriService.Models.Asterisk.Event
{
    public enum AriEventType
    {
        ApplicationMoveFailed = 0,
        ApplicationRegistered = 1,
        ApplicationReplaced = 2,
        ApplicationUnregistered = 3,
        BridgeAttendedTransfer = 4,
        BridgeBlindTransfer = 5,
        BridgeCreated = 6,
        BridgeDestroyed = 7,
        BridgeMerged = 8,
        BridgeVideoSourceChanged = 9,
        CallBroadcast = 10,
        CallClaimed = 11,
        ChannelCallerId = 12,
        ChannelConnectedLine = 13,
        ChannelCreated = 14,
        ChannelDestroyed = 15,
        ChannelDialplan = 16,
        ChannelDtmfReceived = 17,
        ChannelEnteredBridge = 18,
        ChannelHangupRequest = 19,
        ChannelHold = 20,
        ChannelLeftBridge = 21,
        ChannelStateChange = 22,
        ChannelTalkingFinished = 23,
        ChannelTalkingStarted = 24,
        ChannelToneDetected = 25,
        ChannelTransfer = 26,
        ChannelUnhold = 27,
        ChannelUserevent = 28,
        ChannelVarset = 29,
        ContactStatusChange = 30,
        DeviceStateChanged = 31,
        Dial = 32,
        EndpointStateChange = 33,
        PeerStatusChange = 34,
        PlaybackContinuing = 35,
        PlaybackFinished = 36,
        PlaybackStarted = 37,
        RESTResponse = 38,
        RecordingFailed = 39,
        RecordingFinished = 40,
        RecordingStarted = 41,
        StasisEnd = 42,
        StasisStart = 43,
        TextMessageReceived = 44,
    }
    
}